name: CI
on: [push]

jobs:
  build:
    name: flutter build & test
    runs-on: macos-latest
    steps:
      # init actions and flutter
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.4"
          channel: "stable"
      - run: flutter --version

      - name: Test core module
        working-directory: ./core
        run: |
          flutter pub get
          flutter test
      - name: Test about module
        working-directory: ./about
        run: |
          flutter pub get
          flutter test
      - name: Test search module
        working-directory: ./search
        run: |
          flutter pub get
          flutter test

      # android apk build
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - run: flutter build apk
      - run: flutter build appbundle

      # ios build
      - run: flutter build ios --release --no-codesign
